### ISSUE TITLE
Incompatible with latest VSCode  (1.85.1)

### ISSUE THREAD

**Issue by phrontisteries** [recursean/JAR-Viewer-and-Decompiler-VSCode-Extension#1]
Not compatible with latest VSCode version 1.85.1

**Comment by recursean** [comment]
This extension requires VSCode 1.88.0 or newer. The latest version of VSCode is [1.89.0](https://code.visualstudio.com/updates/v1_89). So, yes I would agree that this extension is not compatible with version 1.85.1. Is there a reason you can not upgrade to the latest version of VSCode?

**Comment by recursean** [comment]
Just checking in on this. Should I close the issue?
