### ISSUE TITLE
cfr works but extension does not

### ISSUE THREAD

**Issue by systemmind** [recursean/JAR-Viewer-and-Decompiler-VSCode-Extension#8]
cfr works but extension just crashes when I am trying to open .class file. I think extension may not work well if the .class file path includes spaces.

**Comment by recursean** [comment]
Thanks for trying out the extension! I seem to be able to recreate the issue and will post an update once it is fixed.

**Comment by recursean** [comment]
I just published v1.2.2 of this extension which should resolve your error. Please give it a try and let me know if it fixes your problem. Any other issues can be fixed in future versions of the extension. Thanks!

**Comment by systemmind** [comment]
Hello, @recursean. Yes, the version v1.2.2 works well. Thank you!
